server {
	listen 80;
	root /var/www/html;
	index index.php;
	server_name your-domain.com;

	# increase max file upload
	client_max_body_size 10M;

	# this is very important, be sure its in your nginx conf - it prevents access to logs etc.
	location ~ /system {
		deny all;
	}

	# block .htaccess, CHANGELOG.md, composer.json etc.
	# this is to prevent finding software versions
	location ~\.(ht|md|json|dist|sql)$ {
		deny all;
	}

	# block git files and folders
	location ~ /\.git {
		deny all;
	}

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_read_timeout 240;
	}
}
